---
title: "Contribute to NVIdb"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Contribute to NVIdb}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Thank you for taking interest in contributing to *NVIdb*. 

There are several ways you can contribute to the development of *NVIdb*: reporting a bug, fixing documentation errors, contributing new code, or commenting on issues/pull requests. Note that the majority of these activities do not require you to be proficient in R.

All new code or documentation must be approved by @PetterHopp. 


### Commenting on Issues / Pull Requests

All are welcome to comment on issues or pull requests regardless if they are directly involved in creating them or maintaining *NVIdb*.


### Raising an Issue / Reporting a Bug

The issue tracker is for both Bug Reports and Feature Requests. If you think you
have found a bug, you can raise an issue by going to [`https://github.com/NorwegianVeterinaryInstitute/NVIdb/issues`](https://github.com/NorwegianVeterinaryInstitute/NVIdb/issues) and submit a reproducible example. 

Here are some guidelines to help make the process go smoothly:


#### Ensure your R version and NVIdb version are up-to-date.

To check your versions of R and NVIdb, you can run the following code

```r
R.version.string
packageVersion("NVIdb")
```

Your output will look something like this:

```r
R.version.string
#> [1] "R version 4.0.2 (2020-06-22)"
packageVersion("NVIdb")
#> [1] '0.1.6'
```

You can check this against the versions reported at [`https://r-project.org`](https://r-project.org) and in the [DESCRIPTION](https://github.com/NorwegianVeterinaryInstitute/NVIdb/blob/master/DESCRIPTION) for *NVIdb*.


#### Make sure your problem is reproducible and minimal

When filing an issue, the most important thing is to include a minimal 
reproducible example to ensure that the maintainers will be able to verify the 
problem, and then figure out how to fix it. There are three things you need to 
include to make your example reproducible: required packages, data, code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs.

1.  The easiest way to include **data** is to use `dput()` to generate the R code 
    to recreate it. For example, to recreate the `mtcars` dataset in R,
    I'd perform the following steps:
  
       1. Run `dput(mtcars)` in R
       2. Copy the output
       3. In my reproducible script, type `mtcars <- ` then paste.
       
    For large datasets, please include a subset of the dataset that is sufficient
    to reproduce the problem.
  
1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:
  
    * make sure you've used spaces and your variable names are concise, but
      informative
  
    * use comments to indicate where your problem lies
  
    * do your best to remove everything that is not related to the problem.  
     The shorter your code is, the easier it is to understand.
     

### Updating Documentation

If you see a spelling error, grammatical error or you have a better way of 
phrasing an error message, vignette entry, or manual page, feel free to 
contribute. Getting help with this is really appreciated!

All functions are documented using [roxygen2](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html) comments above the functions themselves. If you want to edit documentation, 
please make the changes there and make sure you include the roxygen comment 
(`#'`) in front of your additions.  


#### If you are not experienced with git/GitHub

You can make changes directly on GitHub by clicking the little pencil icon in 
the top right corner of the file when you view it on GitHub When you do that, 
GitHub will create a copy of the *NVIdb* repository in your account so you can 
edit the file. When you are done editing the file, you may click on "Propose 
File Change" at the bottom of the page (You can also add a short commit message 
or leave the entries blank). From there, you will be taken the form to create a 
Pull Request, where you can review your changes and click "Create Pull Request". 
Details can be found here: [`https://help.github.com/articles/editing-files-in-another-user-s-repository/`](https://help.github.com/articles/editing-files-in-another-user-s-repository/).


#### If you are experienced with git/GitHub

1.  fork NVIdb to your GitHub account

1.  clone NVIdb to your desktop 

1.  create a new branch from main and push/sync to your repository

1.  make and commit your changes

1.  update the documentation with roxygen2


### Contributing New Code

If you want to contribute code, you are welcome to do so. Please try to adhere 
to some principles and style convention used in *NVIdb*. 

*   I try to limit the number of package dependencies for *NVIdb*. Use of base 
commands is much appreciated. If you want to write code in `dplyr`-style, you 
may consider using the package [poorman](https://cran.r-project.org/package=poorman).

*   New code should generally follow the tidyverse [style guide](http://style.tidyverse.org). 
I recommend to use the [styler](https://CRAN.R-project.org/package=styler) 
package to apply spaces: `styler::style_file(filename, scope = "spaces")`. 
Please don't restyle code that has nothing to do with your pull request.

*   You should add a bullet point to `NEWS.md` motivating the change.

*   You should add yourself as a contributor to the `DESCRIPTION`.

*   If you're adding a new function or new arguments to an existing function, you'll also need
    to document them. *NVIdb* uses [roxygen2](https://cran.r-project.org/package=roxygen2), with
[Markdown syntax](https://cran.r-project.org/web/packages/roxygen2/vignettes/markdown.html),
for documentation. Make sure to re-run `devtools::document()` on the code before submitting. 

*   *NVIdb* uses functions from [checkmate](https://CRAN.R-project.org/package=checkmate) package  for argument checking. Adding argument checking for new functions and/or arguments will be highly appreciated.
    
*   If you can, also write a test. *NVIdb* uses [testthat](https://cran.r-project.org/package=testthat) for tests.

*   Also run `devtools::check()` to make sure your function doesn't imply downstream errors or warnings. 


#### Git Commit Standards
We follow the commit message style guide maintained within the angular.js project.

The start of commit messages should be one of the following:

*   feat: A new feature
*   fix: A bug fix
*   doc: Documentation only changes
*   style: Changes that do not affect the meaning of the code (white-space, 
formatting, missing semi-colons, etc)
*   refactor: A code change that neither fixes a bug or adds a feature
*   perf: A code change that improves performance
*   test: Adding missing tests
*   chore: Changes to the build process or auxiliary tools and libraries such as
documentation generation

Do not capitalize the first letter.


### References
Based on [CONTRIBUTING to poppr](https://github.com/grunwaldlab/poppr/blob/main/CONTRIBUTING.md) by @zkamvar and [CONTRIBUTING to dittodb](https://raw.githubusercontent.com/ropensci/dittodb/main/CONTRIBUTING.mdd) by @jonkeane.

